### ISSUE TITLE
Allow OIDC to be used

### ISSUE THREAD

**Issue by neil-hickey** [cloudfoundry-incubator/kubo-disaster-recovery-acceptance-tests#4]
Hello!

The PKS team will need to be able to use OIDC as the auth provider while running the DRATS tests.

As far as I'm aware, all that needs to be added is the following library for the `client-go` library to work with OIDC:

`_ "k8s.io/client-go/plugin/pkg/client/auth" // load oidc auth`

**Comment by jamesjoshuahill** [comment]
Hi @neil-hickey 

That sounds good to us. Please could you submit a PR?

Many thanks
Josh and @aclevername

**Comment by gmrodgers** [comment]
Closed due to lack of activity
